spring:
    application:
        name: teamwork-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
        
server:
    port: 8765 #启动端口
    
zuul:
  #prefix: /techouse #为zuul设置一个公共的前缀
  #ignoredServices: '*'
  routes:
    admin-ui: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
      path: /admin/** #匹配/techouse/usersystem/** 均路由到cloud-client
    admin-back:
      path: /back/**
      
ribbon:
  eureka:
    enabled: false #配置zuul路由时用将此属性设置为false

admin-ui:
  ribbon:
    listOfServers: 127.0.0.1:8766 #为cloud-client服务指定一组服务地址，应该是用于负载均衡
admin-back:
  ribbon:
    listOfServers: 127.0.0.1:8762

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
security:
    user:
        name: teamwork
        password: 123456
        role: USER